var nombre="David";
var apellido="Verna";
console.log(nombre + " " + apellido);
var numero1= 56;
var numero2= 24;
var suma= numero1 + numero2;
console.log("La suma de numero1 y numero2 es: " + suma);
var numero3= 38;
var resultado= suma + numero3;
console.log("la suma del resultado anterior, más el tercer número es: " + resultado);